import { test, expect } from '@playwright/test';

test('edit company', async ({ page }) => {
  await page.goto('https://dev.regalis.app/');
  await page.getByPlaceholder('メールアドレスを入力する').click();
  await page.getByPlaceholder('メールアドレスを入力する').fill('shunwasaki144@gmail.com');
  await page.getByPlaceholder('パスワードを入力する').click();
  await page.getByPlaceholder('パスワードを入力する').fill('Test@123!');
  await page.getByRole('button', { name: 'ログイン' }).click();
  await page.getByText('求人企業リスト').click();
  await page.getByText('企業リスト', { exact: true }).click();
  await page.getByRole('cell', { name: '00013' }).click();
  await page.getByRole('button', { name: '編 集' }).click();
  await page.getByPlaceholder('会社名を入力する').click();
  await page.getByPlaceholder('会社名を入力する').clear();
  await page.getByPlaceholder('会社名を入力する').fill('new company');
  await page.getByPlaceholder('支店・部署名を入力する').click();
  await page.getByPlaceholder('支店・部署名を入力する').clear();
  await page.getByPlaceholder('支店・部署名を入力する').fill('new department');
  await page.getByPlaceholder('担当者名を入力する').click();
  await page.getByPlaceholder('担当者名を入力する').clear();
  await page.getByPlaceholder('担当者名を入力する').fill('new name');
  await page.getByPlaceholder('所在地を入力する').click();
  await page.getByPlaceholder('所在地を入力する').clear();
  await page.getByPlaceholder('所在地を入力する').fill('test');
  await page.getByPlaceholder('電話番号を入力する').click();
  await page.getByPlaceholder('電話番号を入力する').clear();
  await page.getByPlaceholder('電話番号を入力する').fill('test');
  await page.close();
});
test.only('cancel edit company', async ({ page }) => {
    await page.goto('https://dev.regalis.app/');
    await page.getByPlaceholder('メールアドレスを入力する').click();
    await page.getByPlaceholder('メールアドレスを入力する').fill('shunwasaki144@gmail.com');
    await page.getByPlaceholder('パスワードを入力する').click();
    await page.getByPlaceholder('パスワードを入力する').fill('Test@123!');
    await page.getByRole('button', { name: 'ログイン' }).click();
    await page.getByText('求人企業リスト').click();
    await page.getByText('企業リスト', { exact: true }).click();
    await page.getByRole('cell', { name: '00013' }).click();
    await page.getByRole('button', { name: '編 集' }).click();
    await page.getByPlaceholder('会社名を入力する').click();
    await page.getByPlaceholder('会社名を入力する').clear();
    await page.getByPlaceholder('会社名を入力する').fill('new company');
    await page.getByPlaceholder('支店・部署名を入力する').click();
    await page.getByPlaceholder('支店・部署名を入力する').clear();
    await page.getByPlaceholder('支店・部署名を入力する').fill('new department');
    await page.getByPlaceholder('担当者名を入力する').click();
    await page.getByPlaceholder('担当者名を入力する').clear();
    await page.getByPlaceholder('担当者名を入力する').fill('new name');
    await page.getByPlaceholder('所在地を入力する').click();
    await page.getByPlaceholder('所在地を入力する').clear();
    await page.getByPlaceholder('所在地を入力する').fill('test');
    await page.getByPlaceholder('電話番号を入力する').click();
    await page.getByPlaceholder('電話番号を入力する').clear();
    await page.getByPlaceholder('電話番号を入力する').fill('test');
    await page.getByRole('button', { name: 'キャンセル' }).click();
    await page.close();
  });
